{
 "title": "dashboard perbankan",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error 400",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_bucket{status=\"400\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_bucket{status=\"500\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_duration_count[5m]))",
     "legendFormat": "{{method}} - {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}